name: CI

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

 workflow_dispatch:



jobs:
  build-and-realease:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Run a one-line script
       run: echo Hello,world!

     - name: Run a mutli-line script
       run: |
         echo Add other actions to build.
         echo test, and deploy your project.
